# -*- coding: utf-8 -*-
"""Learning-rate schedule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHDGHGAfoqPQkk4GEhEwyd-I1Q-KFQTh
"""

# --------- Learning-rate schedule ----------
def lr_schedule(epoch, lr):
    if epoch < 90:
        return 1e-3
    elif epoch < 145:
        return 1e-4
    else:
        return 1e-5