# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHM6KYcD9MQExzlUxb0vTVXkxK5qAdR7
"""

# ---------- 0) Imports ----------
import os, json, random
import numpy as np
import pandas as pd

from zipfile import ZipFile

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    matthews_corrcoef, cohen_kappa_score, roc_auc_score
)

import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.layers import Input, Dense, Conv1D, GlobalAveragePooling1D, LSTM, Concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, LearningRateScheduler

# ---------- 2) Load dataset ----------
df = pd.read_csv(df_path)

print(df.info())
print(df.head())

# ---------- 3) Define features and labels ----------
# Current features
feature_columns = ['p', 'q', 'r', 'ax', 'ay', 'az', 'Φ', 'Θ', 'Ψ']
# Motor fault columns used ONLY to define labels (then excluded from inputs)
motor_fault_cols = ['m1', 'm2', 'm3', 'm4']

# ---------- 4) Fault severity labeling ----------
def classify_fault(row):
    max_fault_value = max(row['m1'], row['m2'], row['m3'], row['m4'])
    if max_fault_value >= 0.40:
        return 'Fault 8'
    elif max_fault_value >= 0.35:
        return 'Fault 7'
    elif max_fault_value >= 0.30:
        return 'Fault 6'
    elif max_fault_value >= 0.25:
        return 'Fault 5'
    elif max_fault_value >= 0.20:
        return 'Fault 4'
    elif max_fault_value >= 0.15:
        return 'Fault 3'
    elif max_fault_value >= 0.10:
        return 'Fault 2'
    elif max_fault_value >= 0.05:
        return 'Fault 1'
    else:
        return 'No Fault'

df['fault_classification'] = df.apply(classify_fault, axis=1)

label_encoder = LabelEncoder()
df['label_encoded'] = label_encoder.fit_transform(df['fault_classification'])
num_classes = len(label_encoder.classes_)

print("\nClasses:", list(label_encoder.classes_))
print("num_classes:", num_classes)

# ---------- 5) Prepare X and y ----------
X_all = df[feature_columns].values.astype(np.float32)
y_all = df['label_encoded'].values.astype(np.int32)


# ---------- 6) Reproducibility ----------
def set_all_seeds(seed: int):
    np.random.seed(seed)
    random.seed(seed)
    tf.random.set_seed(seed)